# Generated by Django 5.2.4 on 2025-07-19 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScholarshipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=50)),
                ('academic_year', models.CharField(max_length=20)),
                ('units_enrolled', models.IntegerField()),
                ('swa_grade', models.DecimalField(decimal_places=2, max_digits=5)),
                ('grade_document', models.FileField(blank=True, null=True, upload_to='grade_documents/')),
                ('has_inc_withdrawn', models.BooleanField(default=False)),
                ('has_failed_dropped', models.BooleanField(default=False)),
                ('ai_verification_status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('under_review', 'Under AI Review')], default='pending', max_length=20)),
                ('ai_confidence_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ai_verification_notes', models.TextField(blank=True)),
                ('base_allowance', models.DecimalField(decimal_places=2, default=5000.0, max_digits=10)),
                ('merit_incentive', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_allowance', models.DecimalField(decimal_places=2, default=5000.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AIVerificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_type', models.CharField(max_length=50)),
                ('input_data', models.TextField()),
                ('ai_response', models.TextField()),
                ('confidence_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.scholarshipapplication')),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('university', models.CharField(default='Taguig City University', max_length=100)),
                ('course', models.CharField(blank=True, max_length=100)),
                ('year_level', models.CharField(blank=True, max_length=20)),
                ('is_first_time_applicant', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.studentprofile'),
        ),
    ]
