# Generated by Django 5.2.3 on 2025-07-19 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_scholarshipapplication_aiverificationlog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarshipapplication',
            name='has_failed_dropped',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='scholarshipapplication',
            name='has_inc_withdrawn',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='scholarshipapplication',
            name='swa_grade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='scholarshipapplication',
            name='units_enrolled',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
